on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: Basic

jobs:

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.68.2
          target: wasm32-unknown-unknown
          override: true

      - name: Install Cargo Make
        uses: davidB/rust-cargo-make@v1

      - name: Run test
        run: cargo make test

      - name: Build
        run: cargo make build